### ISSUE TITLE
Scope of exploit in Thymeleaf

### ISSUE THREAD

**Issue by OrangeDog** [p1n93r/SpringBootAdmin-thymeleaf-SSTI#1]
Am I correct that this only affects Thymeleaf if it's given untrusted templates, or is there a flaw with variable inclusion / expression evaluation somewhere?

**Comment by p1n93r** [comment]
Hi @OrangeDog
In theory, this can affect other products that use Thymeleaf for template rendering. However, it is necessary to have control over the template content being rendered by Thymeleaf in order to exploit this vulnerability.

In the case of springboot-admin, Thymeleaf is used for template rendering, and the template content that can be controlled by attackers leads to the successful exploitation of the vulnerability. If other products that depend on Thymeleaf also allow attackers to control the template content being rendered, this vulnerability can also occur.

**Comment by OrangeDog** [comment]
"template content" means the template itself, not anything in the context that may get rendered into it?

**Comment by p1n93r** [comment]
Yes. The sandbox bypass mentioned here refers to bypassing certain blacklists of Thymeleaf, rather than leveraging the context for reflection-based escapes or similar techniques.

**Comment by OrangeDog** [comment]
Thanks for clarifying. You might like to put that at the top of the readme, for all the other people who are going to come here from their CVE detection tools.
